openapi: 3.1.0
info:
  title: openapi-spec
  version: '1.0'
  summary: For act-server
servers:
  - url: 'http://localhost:12212'
paths:
  /app/storage:
    parameters: []
    post:
      summary: Batch get storage
      operationId: post-app-storage
      responses:
        '200':
          $ref: '#/components/responses/storagesResponse'
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
        description: ''
      security:
        - JWT-Authrization: []
      description: ''
  '/admin/storage/{storage_key}':
    parameters:
      - schema:
          type: string
        name: storage_key
        in: path
        required: true
    get:
      summary: Get storage info
      tags: []
      responses:
        '200':
          $ref: '#/components/responses/storageResponse'
      operationId: get-admin-storage_id
      security:
        - X-InternalAuthorization: []
      description: ''
    put:
      summary: Update storage
      operationId: put-admin-storage_id
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StorageRequest'
      security:
        - X-InternalAuthorization: []
    delete:
      summary: Delete storage
      operationId: delete-admin-storage_id
      responses:
        '200':
          description: OK
      security:
        - X-InternalAuthorization: []
  /admin/storage:
    post:
      summary: Create Storage
      operationId: post-admin-storage
      responses:
        '200':
          description: OK
      security:
        - X-InternalAuthorization: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StorageRequest'
  /admin/storages:
    post:
      summary: Admin batch get storages by keys
      operationId: post-admin-storages
      responses:
        '200':
          $ref: '#/components/responses/storagesResponse'
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
      security:
        - X-InternalAuthorization: []
      description: ''
    parameters: []
    get:
      summary: Admin get all storages
      operationId: get-admin-storages
      responses:
        '200':
          $ref: '#/components/responses/storagesResponse'
      security:
        - X-InternalAuthorization: []
  '/admin/permission/{permission_id}':
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          $ref: '#/components/responses/permissionResponse'
      operationId: get-admin-permission
      description: ''
      security:
        - X-InternalAuthorization: []
    put:
      summary: ''
      operationId: put-admin-permission
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PermissionRequest'
      security:
        - X-InternalAuthorization: []
    delete:
      summary: ''
      operationId: delete-admin-permission
      responses:
        '200':
          description: OK
      security:
        - X-InternalAuthorization: []
    parameters:
      - schema:
          type: string
        name: permission_id
        in: path
        required: true
  /admin/permission:
    post:
      summary: ''
      operationId: post-admin-permission
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PermissionRequest'
      security:
        - X-InternalAuthorization: []
  /admin/permissions:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          $ref: '#/components/responses/permissionsResponse'
      operationId: get-admin-permissions
      security:
        - X-InternalAuthorization: []
    post:
      summary: ''
      operationId: post-admin-permissions
      responses:
        '200':
          description: OK
      security:
        - X-InternalAuthorization: []
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
components:
  schemas:
    StorageResponse:
      title: StorageResponse
      x-stoplight:
        id: qmt3u6ymcguxu
      type: object
      properties:
        key:
          type: string
        value:
          type: string
        need_permissions:
          type: array
          items:
            type: string
        need_permission_count:
          type: integer
        comment:
          type: string
      required:
        - key
        - value
        - need_permissions
        - need_permission_count
        - comment
    StorageRequest:
      title: StorageRequest
      x-stoplight:
        id: qmt3u6ymcguxu
      type: object
      properties:
        key:
          type: string
        value:
          type: string
        need_permissions:
          type: array
          items:
            type: string
        need_permission_count:
          type: integer
        comment:
          type: string
      required:
        - key
    PermissionResponse:
      title: PermissionResponse
      x-stoplight:
        id: 5pk2wpi5pur7w
      type: object
      properties:
        id:
          type: string
        comment:
          type: string
      required:
        - id
    PermissionRequest:
      title: PermissionRequest
      x-stoplight:
        id: hh2wlqjltly4q
      type: object
      properties:
        id:
          type: string
        comment:
          type: string
      required:
        - id
  securitySchemes:
    JWT-Authrization:
      type: http
      scheme: bearer
      description: Authrization with permission List
    X-InternalAuthorization:
      name: xxx
      type: apiKey
      in: header
  responses:
    storageResponse:
      description: Example response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/StorageResponse'
    storagesResponse:
      description: Example response
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/StorageResponse'
    permissionResponse:
      description: Example response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PermissionResponse'
    permissionsResponse:
      description: Example response
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/PermissionResponse'
