openapi: 3.1.0
info:
  title: openapi-spec
  version: '1.0'
  summary: For act-server
  description: |-
    If you are trying to figure out admin api, see `/admin/sudo` first please.

    Use RFC-3339 as time format.
servers:
  - url: 'http://localhost:12212'
paths:
  /app/storage:
    parameters: []
    post:
      summary: Batch get storage
      operationId: post-app-storage
      responses:
        '200':
          $ref: '#/components/responses/storagesSimpleResponse'
      security:
        - JWT-Authrization: []
      description: Normal user get all storage value by keys which embed in jwt authrization.
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
        description: ''
      x-internal: false
  '/admin/storage/{storage_key}':
    parameters:
      - schema:
          type: string
        name: storage_key
        in: path
        required: true
    get:
      summary: Get storage info
      tags: []
      responses:
        '200':
          $ref: '#/components/responses/storageResponse'
      operationId: get-admin-storage_id
      description: |
        Get key/value storage info by stroage key.

        Need admin token which has `read` permission on `X-internalAuthorization` header.
      x-internal: true
      security:
        - X-InternalAuthorization: []
    put:
      summary: Update storage
      operationId: put-admin-storage_id
      responses:
        '204':
          description: No Content
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StorageRequest'
        description: ''
      security:
        - X-InternalAuthorization: []
      description: |-
        Update key/value storage.

        `key` in request body will be ignore.

        Need admin token which has `write` permission on `X-internalAuthorization` header.
      x-internal: true
    delete:
      summary: Delete storage
      operationId: delete-admin-storage_id
      responses:
        '204':
          description: No Content
      security:
        - X-InternalAuthorization: []
      description: |-
        Delete key/value storage by storage_key.

        Need admin token which has `write` permission on `X-internalAuthorization` header.
      x-internal: true
  /admin/storage:
    post:
      summary: Create Storage
      operationId: post-admin-storage
      responses:
        '204':
          description: No Content
      security:
        - X-InternalAuthorization: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StorageRequest'
      description: |-
        Create a record in key/value storage.

        Need admin token which has `write` permission on `X-internalAuthorization` header.
      x-internal: true
  /admin/storages:
    post:
      summary: Admin get storages by keys
      operationId: post-admin-storages
      responses:
        '200':
          $ref: '#/components/responses/storagesResponse'
      requestBody:
        content:
          application/json:
            schema:
              type: array
              description: array of storage key
              items:
                type: string
        description: ''
      security:
        - X-InternalAuthorization: []
      description: |-
        Admin get storages by keys.

        Need admin token which has `read` permission on `X-internalAuthorization` header.
      x-internal: true
    parameters: []
    get:
      summary: Get all storages
      operationId: get-admin-storages
      responses:
        '200':
          $ref: '#/components/responses/storagesResponse'
      description: |
        Return all storages.

        Need admin token which has `read` permission on `X-internalAuthorization` header.
      security:
        - X-InternalAuthorization: []
  /admin/storages/query:
    parameters: []
    post:
      summary: Admin get storages by query params
      operationId: post-admin-storages-query
      responses:
        '200':
          $ref: '#/components/responses/storagesResponse'
      security:
        - X-InternalAuthorization: []
      description: |
        Get storage by query params in request body.

        if request body is empty, will return all storages.

        include_permission will effect first.

        Need admin token which has `read` permission on `X-internalAuthorization` header.
      x-internal: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                include_permission:
                  type: array
                  description: array of permission id
                  items:
                    type: string
                exclude_permission:
                  type: array
                  description: array of permission id
                  items:
                    type: string
          application/xml:
            schema:
              type: object
              properties:
                include_permission:
                  type: array
                  items:
                    type: string
                exclude_permission:
                  type: array
                  items:
                    type: string
        description: ''
  '/admin/permission/{permission_id}':
    get:
      summary: Admin get permission info
      tags: []
      responses:
        '200':
          $ref: '#/components/responses/permissionResponse'
      operationId: get-admin-permission
      description: |-
        Admin get permission info by permission id.

        Need admin token which has `read` permission on `X-internalAuthorization` header.
      security:
        - X-InternalAuthorization: []
      x-internal: true
    put:
      summary: Admin update permission
      operationId: put-admin-permission
      responses:
        '204':
          description: No Content
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PermissionRequest'
      security:
        - X-InternalAuthorization: []
      description: |-
        Admin update permission.

        permission_id in request body will be ignored.

        Need admin token which has `write` permission on `X-internalAuthorization` header.
      x-internal: true
    delete:
      summary: Admin delete permission
      operationId: delete-admin-permission
      responses:
        '204':
          description: No Content
      security:
        - X-InternalAuthorization: []
      description: |
        Admin delete permission.

        Need admin token which has `write` permission on `X-internalAuthorization` header.
      x-internal: true
    parameters:
      - schema:
          type: string
        name: permission_id
        in: path
        required: true
  /admin/permission:
    post:
      summary: Admin create permission
      operationId: post-admin-permission
      responses:
        '204':
          description: No Content
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PermissionRequest'
      security:
        - X-InternalAuthorization: []
      description: |
        Admin create permission.

        Need admin token which has `write` permission on `X-internalAuthorization` header.
      x-internal: true
  /admin/permissions:
    post:
      summary: Admin get permission by permission id
      operationId: post-admin-permissions
      responses:
        '200':
          description: OK
      security:
        - X-InternalAuthorization: []
      requestBody:
        content:
          application/json:
            schema:
              type: array
              description: array of permission id
              items:
                type: string
      description: |-
        Admin get permission by permission id.

        Need admin token which has `read` permission on `X-internalAuthorization` header.
      x-internal: true
    get:
      summary: Get all permissions
      operationId: get-admin-permissions
      responses:
        '200':
          $ref: '#/components/responses/permissionsResponse'
      security:
        - X-InternalAuthorization: []
      description: |-
        Return all permissions.

        Need admin token which has `read` permission on `X-internalAuthorization` header.
  /admin/permissions/query:
    post:
      summary: Admin get permission by query params
      tags: []
      responses:
        '200':
          $ref: '#/components/responses/permissionsResponse'
      operationId: get-admin-permissions
      security:
        - X-InternalAuthorization: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                regex:
                  type: string
        description: ''
      description: |
        Admin get permission by query params in request body.

        `regex` key in request body is a regex express, will return all permissions fit this regex expresss. 
        if request body is empty, will return all permissions.

        Need admin token which has `read` permission on `X-internalAuthorization` header.
      x-internal: true
    parameters: []
  '/admin/token/{token}':
    parameters:
      - schema:
          type: string
        name: token
        in: path
        required: true
    put:
      summary: Update token info
      operationId: put-admin-authrization_token
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRequest'
      responses:
        '204':
          description: No Content
      security:
        - X-InternalAuthorization: []
      x-internal: true
      description: |-
        Update token info.

        Need admin token which has `sudo` permission on `X-internalAuthorization` header.
    delete:
      summary: Admin delete token
      operationId: delete-admin-authrization_token
      responses:
        '204':
          description: No Content
      security:
        - X-InternalAuthorization: []
      x-internal: true
      description: |-
        Admin delete token.

        Need admin token which has `sudo` permission on `X-internalAuthorization` header.
    get:
      summary: Admin get token info
      operationId: get-admin-token
      responses:
        '200':
          $ref: '#/components/responses/tokenResponse'
      x-internal: true
      description: |
        Admin get token info.
  /admin/token:
    post:
      summary: Admin create new token
      operationId: post-admain-token
      responses:
        '204':
          description: No Content
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRequest'
      security:
        - X-InternalAuthorization: []
      x-internal: true
      description: |
        Admin create new token.

        Need admin token which has `sudo` permission on `X-internalAuthorization` header.
    parameters: []
  /admin/tokens:
    get:
      summary: Admin get all tokens
      tags: []
      responses:
        '200':
          $ref: '#/components/responses/tokensResponse'
      operationId: get-admin-auth-tokens
      parameters: []
      security:
        - X-InternalAuthorization: []
      x-internal: true
      description: |-
        Admin get all tokens.

        Need admin token which has `sudo` permission on `X-internalAuthorization` header.
    post:
      summary: Admin get tokens by token id
      operationId: post-admin-auth-tokens
      responses:
        '200':
          $ref: '#/components/responses/tokensResponse'
      requestBody:
        content:
          application/json:
            schema:
              type: array
              description: array of token id
              items:
                type: string
        description: 'if request body is empty, return all tokens.'
      description: |
        Admin get tokens by token id.

        Need admin token which has `sudo` permission on `X-internalAuthorization` header.
      security:
        - X-InternalAuthorization: []
      x-internal: true
    parameters: []
  /admin/sudo:
    post:
      summary: Get sudo token
      operationId: post-admin-sudo
      responses:
        '200':
          $ref: '#/components/responses/rawTokenResponse'
      description: |-
        Temperature get a highest permission admin token, which will expired in 5 mintues.
        Use this token create new token by `/admin/token/xxx` apis.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                root_token:
                  type: string
              required:
                - root_token
      x-internal: true
  /admin/temp_user_token:
    get:
      summary: Admin get temp user token
      tags: []
      responses:
        '200':
          $ref: '#/components/responses/rawTokenResponse'
      operationId: get-admin-temp_token
      description: |-
        Generate an temp user token with all permissions and expired in 5 minutes for `/app/storage` api for test.

        Need admin token which has `read` permission on `X-internalAuthorization` header.
      security:
        - X-InternalAuthorization: []
      x-internal: true
    parameters: []
components:
  schemas:
    StorageResponse:
      title: StorageResponse
      x-stoplight:
        id: qmt3u6ymcguxu
      type: object
      description: ''
      properties:
        key:
          type: string
        value:
          type: string
        need_permissions:
          type: array
          description: array of permission id
          items:
            type: string
        need_permission_count:
          type: integer
        comment:
          type: string
      required:
        - key
        - value
        - need_permissions
        - need_permission_count
        - comment
    StorageRequest:
      title: StorageRequest
      x-stoplight:
        id: qmt3u6ymcguxu
      type: object
      properties:
        key:
          type: string
        value:
          type: string
        need_permissions:
          type: array
          items:
            type: string
        need_permission_count:
          type: integer
        comment:
          type: string
      required:
        - key
        - value
    StorageSimpleResponse:
      title: StorageSimpleResponse
      x-stoplight:
        id: tlvsw8j9rl1nt
      type: object
      properties:
        key:
          type: string
        value:
          type: string
      required:
        - key
        - value
    PermissionResponse:
      title: PermissionResponse
      x-stoplight:
        id: 5pk2wpi5pur7w
      type: object
      properties:
        id:
          type: string
        comment:
          type: string
      required:
        - id
    PermissionRequest:
      title: PermissionRequest
      x-stoplight:
        id: hh2wlqjltly4q
      type: object
      properties:
        id:
          type: string
        comment:
          type: string
      required:
        - id
    TokenRequest:
      title: TokenRequest
      x-stoplight:
        id: xkj945hqugj19
      type: object
      description: 'if `token` in request is empty, it will generate by backend'
      properties:
        admin_permission:
          type: array
          items:
            $ref: '#/components/schemas/AdminPermission'
        comment:
          type: string
        token:
          type: string
        expired_at:
          type: string
          description: 'defaut: 30 days'
        is_valid:
          type: boolean
          description: 'default: true'
      required:
        - admin_permission
    TokenResponse:
      title: TokenResponse
      x-stoplight:
        id: ffhfz5wptg7kp
      type: object
      properties:
        token:
          type: string
        admin_permission:
          type: array
          items:
            type: string
        comment:
          type: string
        expired_at:
          type: string
        is_valid:
          type: boolean
        type:
          type: string
          enum:
            - sudo
            - admin
      required:
        - token
        - admin_permission
        - comment
        - type
    AdminPermission:
      type: string
      title: AdminPermission
      x-stoplight:
        id: m6kotko76v9bt
      enum:
        - read
        - write
        - sudo
    RawTokenResponse:
      title: RawTokenResponse
      x-stoplight:
        id: iw0trifdwfswe
      type: object
      properties:
        token:
          type: string
      required:
        - token
  securitySchemes:
    JWT-Authrization:
      type: http
      scheme: bearer
      description: Authrization with permission List
    X-InternalAuthorization:
      name: xxx
      type: apiKey
      in: header
  responses:
    storageResponse:
      description: Example response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/StorageResponse'
    storagesResponse:
      description: Example response
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/StorageResponse'
    permissionResponse:
      description: Example response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PermissionResponse'
    permissionsResponse:
      description: Example response
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/PermissionResponse'
    tokenResponse:
      description: Example response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/TokenResponse'
    rawTokenResponse:
      description: Example response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RawTokenResponse'
    tokensResponse:
      description: Example response
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/TokenResponse'
    storagesSimpleResponse:
      description: Example response
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/StorageSimpleResponse'
